//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno_Turma
    {
        public int Aluno_Turma1 { get; set; }
        public Nullable<int> Aluno { get; set; }
        public Nullable<int> Turma { get; set; }
    
        public virtual Aluno Aluno1 { get; set; }
        public virtual Turma Turma1 { get; set; }
    }
}
