//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APCEntities : DbContext
    {
        public APCEntities()
            : base("name=APCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<Aluno> Aluno { get; set; }
        public virtual DbSet<Aluno_Interesse> Aluno_Interesse { get; set; }
        public virtual DbSet<Aluno_Turma> Aluno_Turma { get; set; }
        public virtual DbSet<Interesse> Interesse { get; set; }
        public virtual DbSet<Login_Usuario> Login_Usuario { get; set; }
        public virtual DbSet<Professor> Professor { get; set; }
        public virtual DbSet<Professor_Interesse> Professor_Interesse { get; set; }
        public virtual DbSet<Professor_Turma> Professor_Turma { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<Turma> Turma { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
