//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Professor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Professor()
        {
            this.Professor_Interesse = new HashSet<Professor_Interesse>();
            this.Professor_Turma = new HashSet<Professor_Turma>();
        }
    
        public int Professor_ID { get; set; }
        public Nullable<int> Experiencia { get; set; }
        public Nullable<int> Avaliacao { get; set; }
        public Nullable<int> Potencial { get; set; }
        public Nullable<int> Usuario { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Professor_Interesse> Professor_Interesse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Professor_Turma> Professor_Turma { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
