//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoUsuario
    {
        public int TUID { get; set; }
        public int TipoUsuario1 { get; set; }
        public string DescricaoTipo { get; set; }
    }
}
